"""empty message

Revision ID: 29553af80681
Revises: 8e9b60c87e37
Create Date: 2026-08-15 19:30:17.050573

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29553af80681'
down_revision = '8e9b60c87e37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('expenses_user_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('expenses', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('expenses_user_id_fkey'), 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###
