"""empty message

Revision ID: b3faae81b7b4
Revises: 7b30a4c9d271
Create Date: 2026-10-09 15:29:10.343005

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3faae81b7b4'
down_revision = '7b30a4c9d271'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_transactions_user_date'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_user_date'), ['user_id', 'transaction_date'], unique=False)

    # ### end Alembic commands ###
